# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-30 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0003_auto_20180530_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='star',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
