# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-31 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0005_auto_20180530_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='applabel',
            name='cn_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
