# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-31 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0006_applabel_cn_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applabel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='app_label/icon/'),
        ),
    ]
