# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-01 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0007_applabel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='android_apk',
            field=models.FileField(blank=True, null=True, upload_to='upload/app/apk/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/app/logo/'),
        ),
        migrations.AlterField(
            model_name='applabel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload/app_label/icon/'),
        ),
    ]
