# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-01 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0008_auto_20180601_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnews',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload/short_news/pic/'),
        ),
    ]
