# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-02 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0009_auto_20180601_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='applabel',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
