# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-05 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0010_applabel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='web_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applabel',
            name='web_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
