# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-08 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0012_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applabel',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
