# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-09 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0013_applabel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='leaderboard_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
