# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-17 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residenceinn', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL),
        ),
    ]
