# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-17 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0016_userprofile_inviter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='invitation_code',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
