# Generated by Django 2.0.6 on 2018-06-18 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0019_keyvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inviter', to=settings.AUTH_USER_MODEL),
        ),
    ]
