# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0020_auto_20180618_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
