# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-23 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residenceinn', '0023_appdetail_appdetailimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='app_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
